using System.Reflection;
using System.Text.Json;

namespace StreamsPlayer.Core;

/// <summary>
/// A country's full name in the interface language, from the table embedded as <c>country-names.json</c>.
/// </summary>
/// <remarks>
/// The bank carries ISO 3166-1 alpha-2 codes (<c>STREAM-BANK</c>, the <c>country</c> column); a code is the
/// identity, the name is only what a person reads. The table is generated by
/// <c>tools/build-country-names.ps1</c> from Unicode CLDR and carries every shipped
/// <see cref="InterfaceLanguages"/> entry for every code, which <c>CountryNamesTests</c> enforces.
/// <see cref="System.Globalization.RegionInfo"/> is not used: it answers in the region's own language rather
/// than the language the user chose for the interface.
/// </remarks>
public static class CountryNames
{
    internal const string ResourceName = "country-names.json";

    private static readonly Lazy<IReadOnlyDictionary<string, IReadOnlyDictionary<string, string>>> Table =
        new(Load, LazyThreadSafetyMode.ExecutionAndPublication);

    /// <summary>Every code the table names, uppercase.</summary>
    public static IEnumerable<string> Codes => Table.Value.Keys;

    /// <summary>The full name of <paramref name="code"/> in <paramref name="language"/>, or <c>null</c> for a code the table does not know.</summary>
    public static string? Get(string? code, AppLanguage language)
    {
        if (string.IsNullOrEmpty(code) || !Table.Value.TryGetValue(code, out var names))
        {
            return null;
        }

        return names.TryGetValue(InterfaceLanguages.For(language).DictionaryCode, out var name) ||
               names.TryGetValue(InterfaceLanguages.For(InterfaceLanguages.Fallback).DictionaryCode, out name)
            ? name
            : null;
    }

    /// <summary>
    /// What to print for a facet identifier: the full name when the identifier is a known code, otherwise
    /// the identifier itself - the contract's "unrecognized value stays verbatim as the visible fallback".
    /// </summary>
    public static string Label(string countryId, AppLanguage language) =>
        Get(countryId, language) ?? countryId;

    private static IReadOnlyDictionary<string, IReadOnlyDictionary<string, string>> Load()
    {
        using var resource = Assembly.GetExecutingAssembly().GetManifestResourceStream(ResourceName)
            ?? throw new InvalidOperationException($"Embedded resource '{ResourceName}' is missing from StreamsPlayer.Core.");
        var parsed = JsonSerializer.Deserialize<Dictionary<string, Dictionary<string, string>>>(resource)
            ?? throw new InvalidOperationException($"Embedded resource '{ResourceName}' is empty.");

        var table = new Dictionary<string, IReadOnlyDictionary<string, string>>(parsed.Count, StringComparer.OrdinalIgnoreCase);
        foreach (var (code, names) in parsed)
        {
            table[code] = names;
        }

        return table;
    }
}
