<# Prints the explicit manual release checklist. It changes no remote state. #>
[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'
$root = Split-Path $PSScriptRoot -Parent
Push-Location $root
try {
    $version = (Select-String -Path Directory.Build.props -Pattern '<Version>([^<]+)</Version>').Matches.Groups[1].Value
    if ($version -notmatch '^\d{2}\.\d{4}\.\d{4}$') { throw "Version '$version' must use YY.MMDD.HHmm." }
    [DateTime]::ParseExact($version, 'yy.MMdd.HHmm', [Globalization.CultureInfo]::InvariantCulture) | Out-Null
    $branch = git branch --show-current
    $dirty = git status --porcelain
    Write-Host "StreamsPlayer release checklist for v$version" -ForegroundColor Cyan
    Write-Host "Branch: $branch"
    if ($dirty) { Write-Warning 'Working tree is not clean.' }
    Write-Host @"

1. Confirm all intended changes are committed on main and CI is green.
2. Prepare the release tree, then commit it:
   - Set a new local-time (Europe/Malta) ``YY.MMDD.HHmm`` value in every version field in
     Directory.Build.props, then write the What's new blocks into msix/store-listing.md and
     msix/listing/release-notes/<version>.{en-us,ru,uk}.txt. Confirm the stamp is greater than every
     published version, on every channel - stamps at or below 26.0806.2131 were UTC and read 1-2 h early,
     and the Store has shipped a stamp of its own (26.0806.2225) that GitHub and winget never carried.
     Check it: ./scripts/assert-release-version.ps1 -Version <version>  (release.yml runs the same gate).
   - Regenerate the bundled catalog snapshot and verify it:
     ./tools/build-catalog-snapshot.ps1  and  ./tools/build-catalog-snapshot.ps1 -Check
     A snapshot that is missing, over its size ceiling, or older than the bank currently published
     blocks the release. Never pass -Offline here: it skips exactly that last comparison.
   - README.md and docs/index.html carry no version and must not gain one: the READMEs link
     /releases/latest, and docs/ is generated by tools/site/build-site.ps1 - hand-editing it is reverted
     by the next run. Every surface a user-visible change must reach - its source, its generator and
     its languages - is listed once in DOCS_SURFACES.md; walk it before committing.
3. Run: ./scripts/check.ps1
   Then the final code audit (SP-0180), on the exact candidate, once its code is complete:
   - Run the audit campaign of docs/agent/CODE_AUDIT.md over the candidate and resolve every High and
     Medium finding (fix it, or record the owner's explicit decision to ship with it). Commit the fixes,
     re-run ./scripts/check.ps1 on the result.
   - On a clean committed tree write the verdict from your findings file:
     ./scripts/Write-AuditVerdict.ps1 -FindingsPath <findings.json>   and commit
     release-verdicts/<version>.audit.json. The writer refuses an unresolved High/Medium finding; release.yml
     runs ./scripts/Assert-AuditVerdict.ps1 and refuses a verdict whose audited commit is followed by any
     change outside release-verdicts/ - after a material change, audit again.
4. Run: ./scripts/smoke-playback.ps1
   Publishes the committed tree, then plays a live radio station and a live video stream through the
   shipping binary. Red here blocks the release outright. check.ps1 cannot cover this and never
   could: it exercises this repository's code, and SP-0093 was a defect in the WPF runtime
   underneath it - 858 tests stayed green while the product played nothing and a release shipped.
   A build that plays is the only evidence that it plays. A PASS on a clean tree writes
   release-verdicts/<version>.json (SP-0156); a red run writes nothing.
5. Commit the verdict file release-verdicts/<version>.json, then tag the commit locally:
   git tag v<version>
   The verdict must sit inside the tagged tree - release.yml refuses to build without it, and it must
   name exactly the tagged version. Do not push the tag yet.
6. Build and locally test the package: ./msix/build-msix.ps1 -SelfSign
   The script takes the version from the tag at HEAD and refuses a dirty tree or a HEAD off the tag
   (SP-0156). Trust its test certificate, install the package, launch it.
7. Push the tag only after explicit release approval. release.yml then requires a green CI run for the
   tagged commit, the committed smoke verdict for the tagged version, and the pinned natives in the
   payload; an already published asset is never replaced with different bytes (SP-0156).
8. Verify the four assets release.yml generated: the zip, the
   *-windows-x64-setup.exe installer, and a SHA256 sidecar for each. Then run
   the installer on a machine that does not already have it - a published
   installer nobody has executed is an unverified one, and it is the only
   asset that can leave a broken install behind.
9. Copy a release-specific manifest from winget/templates/ to winget-pkgs,
   replace URL/hash/version, validate it, and submit its pull request.
10. Build the unsigned Store package at the tag: ./msix/build-msix.ps1 (no -SelfSign), upload it,
    update Store listing text/screenshots, then submit for certification.
11. GitHub Pages deploys after CI's documentation and site-sync gates pass for the same commit
    (SP-0156); confirm the site is ready for public visibility.

This command does not tag, push, upload, submit, or publish anything.
"@
}
finally { Pop-Location }
