<# Prints the explicit manual release checklist. It changes no remote state. #>
[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'
$root = Split-Path $PSScriptRoot -Parent
Push-Location $root
try {
    $version = (Select-String -Path Directory.Build.props -Pattern '<Version>([^<]+)</Version>').Matches.Groups[1].Value
    if ($version -notmatch '^\d{2}\.\d{4}\.\d{4}$') { throw "Version '$version' must use YY.MMDD.HHmm." }
    [DateTime]::ParseExact($version, 'yy.MMdd.HHmm', [Globalization.CultureInfo]::InvariantCulture) | Out-Null
    $branch = git branch --show-current
    $dirty = git status --porcelain
    Write-Host "StreamsPlayer release checklist for v$version" -ForegroundColor Cyan
    Write-Host "Branch: $branch"
    if ($dirty) { Write-Warning 'Working tree is not clean.' }
    Write-Host @"

1. Confirm all intended changes are committed on main and CI is green.
2. Run: ./scripts/check.ps1
3. Regenerate the bundled catalog snapshot and commit it, then verify it:
   ./tools/build-catalog-snapshot.ps1  and  ./tools/build-catalog-snapshot.ps1 -Check
   A snapshot that is missing, over its size ceiling, or older than the bank currently published
   blocks the release. Never pass -Offline here: it skips exactly that last comparison.
4. Set a new local-time (Europe/Malta) `YY.MMDD.HHmm` value in every version field in Directory.Build.props; update README.md, docs/index.html and msix/store-listing.md. Confirm it is greater than the last published version - stamps at or below 26.0806.2131 were UTC and read 1-2 h early.
5. Build and locally test the package: ./msix/build-msix.ps1 -SelfSign
6. Create and push tag v$version only after explicit release approval.
7. Verify the GitHub Release zip and SHA256 generated by release.yml.
8. Copy a release-specific manifest from winget/templates/ to winget-pkgs,
   replace URL/hash/version, validate it, and submit its pull request.
9. Build an unsigned MSIX with the reserved Partner Center identity, upload it,
   update Store listing text/screenshots, then submit for certification.
10. Publish GitHub Pages only when the site is ready for public visibility.

This command does not tag, push, upload, submit, or publish anything.
"@
}
finally { Pop-Location }
